export const LANGUAGES = {
    python: { ext: 'py', name: 'Python', icon: '🐍', starter: '# Python file\ndef main():\n    print("Hello, World!")\n\nif __name__ == "__main__":\n    main()\n' },
    javascript: { ext: 'js', name: 'JavaScript', icon: '📜', starter: '// JavaScript file\nfunction main() {\n    console.log("Hello, World!");\n}\n\nmain();\n' },
    typescript: { ext: 'ts', name: 'TypeScript', icon: '📘', starter: '// TypeScript file\nfunction main(): void {\n    console.log("Hello, World!");\n}\n\nmain();\n' },
    java: { ext: 'java', name: 'Java', icon: '☕', starter: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}\n' },
    c: { ext: 'c', name: 'C', icon: '🔧', starter: '#include <stdio.h>\n\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}\n' },
    cpp: { ext: 'cpp', name: 'C++', icon: '⚙️', starter: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, World!" << std::endl;\n    return 0;\n}\n' },
    csharp: { ext: 'cs', name: 'C#', icon: '🎯', starter: 'using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine("Hello, World!");\n    }\n}\n' },
    go: { ext: 'go', name: 'Go', icon: '🐹', starter: 'package main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, World!")\n}\n' },
    rust: { ext: 'rs', name: 'Rust', icon: '🦀', starter: 'fn main() {\n    println!("Hello, World!");\n}\n' },
    php: { ext: 'php', name: 'PHP', icon: '🐘', starter: '<?php\n\nfunction main() {\n    echo "Hello, World!\\n";\n}\n\nmain();\n' },
    ruby: { ext: 'rb', name: 'Ruby', icon: '💎', starter: '# Ruby file\ndef main\n  puts "Hello, World!"\nend\n\nmain\n' },
    swift: { ext: 'swift', name: 'Swift', icon: '🦅', starter: 'import Foundation\n\nfunc main() {\n    print("Hello, World!")\n}\n\nmain()\n' },
    kotlin: { ext: 'kt', name: 'Kotlin', icon: '🎨', starter: 'fun main() {\n    println("Hello, World!")\n}\n' },
    scala: { ext: 'scala', name: 'Scala', icon: '🎭', starter: 'object Main extends App {\n    println("Hello, World!")\n}\n' },
    bash: { ext: 'sh', name: 'Bash', icon: '🐚', starter: '#!/bin/bash\n\necho "Hello, World!"\n' },
    powershell: { ext: 'ps1', name: 'PowerShell', icon: '⚡', starter: '# PowerShell file\nWrite-Host "Hello, World!"\n' },
    sql: { ext: 'sql', name: 'SQL', icon: '🗄️', starter: '-- SQL file\nSELECT \'Hello, World!\' AS message;\n' },
    html: { ext: 'html', name: 'HTML', icon: '🌐', starter: '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Document</title>\n</head>\n<body>\n    <h1>Hello, World!</h1>\n</body>\n</html>\n' },
    css: { ext: 'css', name: 'CSS', icon: '🎨', starter: '/* CSS file */\nbody {\n    margin: 0;\n    padding: 0;\n    font-family: Arial, sans-serif;\n}\n\nh1 {\n    color: #333;\n}\n' },
    json: { ext: 'json', name: 'JSON', icon: '📋', starter: '{\n  "name": "project",\n  "version": "1.0.0",\n  "description": "Project description"\n}\n' },
    yaml: { ext: 'yaml', name: 'YAML', icon: '📄', starter: 'name: project\nversion: 1.0.0\ndescription: Project description\n' },
    markdown: { ext: 'md', name: 'Markdown', icon: '📝', starter: '# Project Title\n\n## Description\n\nWrite your project description here.\n\n## Features\n\n- Feature 1\n- Feature 2\n- Feature 3\n' },
    jsx: { ext: 'jsx', name: 'React', icon: '⚛️', starter: 'import React from "react";\n\nexport default function App() {\n    return <h1>Hello React</h1>;\n}\n' },
    tsx: { ext: 'tsx', name: 'React TS', icon: '⚛️', starter: 'import React from "react";\n\nexport default function App() {\n    return 1>Hello React</h1>;\n}\n' },
    text: { ext: 'txt', name: 'Text', icon: '📄', starter: '' }
};
